make changes to allow optimization for both CPU and Memory configurations for GCP Cloud Functions V2
ubc-cirrus-lab/parrotfish pull request #165
Opened 2024-08-27 14:31 UTC by hdu3

# Changes
* Create new CPU-Memory-Duration function to model the serverless function's execution time based on the CPU and Memory allocation.
* Create new classes to support 2D search for the CPU-Memory space.
* Use Google Cloud `functions_v2` API to programmatically update both the CPU and Memory configuration for the function being optimized.
* Add new flag `GCPv2` to enable 2D optimization.
* Add unit tests for the new Classes.

2024-08-28 01:19 UTC, arshiamoghimi requested changes
The code looks good. Thanks. Other than the minor comments inlined, here are some items you need to fix:
- add documentations in the READMEs (main and configuration at src/configuration/README.md).
- pull the latest version of the main branch
- Fix the merge conflicts

2024-08-28 07:31 UTC, hdu3 commented on src/configuration/defaults.py
> +TERMINATION_THRESHOLD = 4
Thanks for the call out. Changed.

2024-08-28 07:31 UTC, hdu3 commented on src/exploration/explorer.py
> +        # self.cpu_memory_space = np.array()
Removed.

2024-08-28 07:31 UTC, hdu3 commented on src/exploration/explorer_2d.py
> +                    # )
Removed.

2024-08-28 07:32 UTC, hdu3 commented on src/exploration/explorer_2d.py
> +        # )
Removed.

2024-08-28 07:33 UTC, hdu3 commented
> The code looks good. Thanks. Other than the minor comments inlined, here are some items you need to fix:
> 
> * add documentations in the READMEs (main and configuration at src/configuration/README.md).
> * pull the latest version of the main branch
> * Fix the merge conflicts

Thanks for the comment. I've addressed these comments in the new commit.

2024-09-17 18:09 UTC, arshiamoghimi approved these changes

2024-09-17 18:10 UTC, merged